# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_addtime'], 'verbose_name': '文章标题', 'verbose_name_plural': '文章标题'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-t_createtime'], 'verbose_name': '标签名称', 'verbose_name_plural': '标签名称'},
        ),
        migrations.AlterField(
            model_name='art',
            name='a_addtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_info',
            field=models.CharField(max_length=500, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_title',
            field=models.CharField(max_length=255, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_updatetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_createtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='标签简介'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_info',
            field=models.CharField(max_length=300, verbose_name='标签简介'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_name',
            field=models.CharField(max_length=255, verbose_name='标签名称'),
        ),
    ]
