# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180411_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='t_createtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
