# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20180411_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签名称', 'verbose_name_plural': '标签名称'},
        ),
    ]
