# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 03:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20180411_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容'),
        ),
    ]
